steps:
      # Install
      - name: 'gcr.io/cloud-builders/npm'
        args: ['install']
      # Build
      - name: 'gcr.io/cloud-builders/npm'
        args: ['run', 'build']
      # Deploy
      - name: gcr.io/cicd-demo-29fe3/firebase
        args: ['deploy', '--project=cicd-demo-29fe3', '--only=hosting']
